#!/usr/bin/env bash
#setting up hostname in nginx headers

sudo apt-get update
sudo apt-get install -y nginx

hostname=$(hostname)

echo "add_header X-Served-By $hostname;" | sudo tee -a /etc/nginx/sites-enabled/default

sudo service nginx restart
