#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get install -y haproxy

cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg
frontend myfrontend
  bind *:80
  mode http
  default_backend myservers
  timeout client 5000s

backend myservers
  balance roundrobin
  mode http
  timeout client 5000s
  timeout server 5000s
  server 401154-web-01 34.224.17.30:80 check
  server 401154-web-02 52.91.101.235:80 check 
EOL
sudo service haproxy start
