#!/usr/bin/env bash
# This script is displaying "Best School" 10 times,print hi in 9th line

count=1
while [ $count -le 10 ]
do
    echo "Best School"
    if [[ "$count" == '9' ]]
    then
        echo "Hi"
    fi
    ((count++))
done

