#!/usr/bin/env bash
# Displays the contents of the current directory in list format
# where only the part of the name after the first dash is displayed. 

list=$(ls)
for a in $list; do
  echo "$a" | cut -d '-' -f2
done
